services:
  frontend:
    build:
      context: ./frontend
      target: deps
    command: npm run dev -- -H 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
