"""initial schema

Revision ID: 404553cc4bf6
Revises: 
Create Date: 2026-08-13 14:22:25.836580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '404553cc4bf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('githubappconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('private_key_pem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('html_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setup_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_githubappconfig_setup_token'), 'githubappconfig', ['setup_token'], unique=True)
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platformconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anthropic_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openai_compatible_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openai_compatible_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openai_compatible_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'VIEWER', 'DEVELOPER', 'SECURITY_ENGINEER', name='userrole'), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('githubinstallation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('account_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('github_app_config_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['github_app_config_id'], ['githubappconfig.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_githubinstallation_github_app_config_id'), 'githubinstallation', ['github_app_config_id'], unique=False)
    op.create_index(op.f('ix_githubinstallation_installation_id'), 'githubinstallation', ['installation_id'], unique=True)
    op.create_table('policyrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('BLOCK_SEVERITY', 'SUPPRESS_RULE', 'SUPPRESS_LICENSE', name='policyruletype'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criticality_weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspacemembership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'DEVELOPER', 'SECURITY_ENGINEER', name='workspacerole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspacemembership_user_id'), 'workspacemembership', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspacemembership_workspace_id'), 'workspacemembership', ['workspace_id'], unique=False)
    op.create_table('apiendpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('framework', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apiendpoint_target_id'), 'apiendpoint', ['target_id'], unique=False)
    op.create_table('prguardrailscan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'PASSED', 'BLOCKED', 'ERROR', 'OVERRIDDEN', name='prguardrailstatus'), nullable=False),
    sa.Column('new_findings_count', sa.Integer(), nullable=False),
    sa.Column('highest_new_severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_endpoints_count', sa.Integer(), nullable=False),
    sa.Column('override_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prguardrailscan_target_id'), 'prguardrailscan', ['target_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sbomcomponent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('package_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sbomcomponent_target_id'), 'sbomcomponent', ['target_id'], unique=False)
    op.create_table('scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_target_id'), 'scan', ['target_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('dedup_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity'), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'ACCEPTED_RISK', 'FALSE_POSITIVE', 'WONT_FIX', 'MITIGATED', 'REOPENED', name='findingstate'), nullable=False),
    sa.Column('state_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cve_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('kev_listed', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('mitigated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_branch'), 'finding', ['branch'], unique=False)
    op.create_index(op.f('ix_finding_dedup_hash'), 'finding', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_finding_priority_score'), 'finding', ['priority_score'], unique=False)
    op.create_index(op.f('ix_finding_state'), 'finding', ['state'], unique=False)
    op.create_index(op.f('ix_finding_target_id'), 'finding', ['target_id'], unique=False)
    op.create_table('prguardrailfinding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_scan_id', sa.Integer(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ignore_status', sa.Enum('NONE', 'REQUESTED', 'APPROVED', 'REJECTED', name='ignorestatus'), nullable=False),
    sa.Column('ignore_requested_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ignore_requested_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ignore_reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ignore_reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pr_scan_id'], ['prguardrailscan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prguardrailfinding_pr_scan_id'), 'prguardrailfinding', ['pr_scan_id'], unique=False)
    op.create_table('findingstatelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findingstatelog')
    op.drop_index(op.f('ix_prguardrailfinding_pr_scan_id'), table_name='prguardrailfinding')
    op.drop_table('prguardrailfinding')
    op.drop_index(op.f('ix_finding_target_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_state'), table_name='finding')
    op.drop_index(op.f('ix_finding_priority_score'), table_name='finding')
    op.drop_index(op.f('ix_finding_dedup_hash'), table_name='finding')
    op.drop_index(op.f('ix_finding_branch'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_scan_target_id'), table_name='scan')
    op.drop_table('scan')
    op.drop_index(op.f('ix_sbomcomponent_target_id'), table_name='sbomcomponent')
    op.drop_table('sbomcomponent')
    op.drop_table('project')
    op.drop_index(op.f('ix_prguardrailscan_target_id'), table_name='prguardrailscan')
    op.drop_table('prguardrailscan')
    op.drop_index(op.f('ix_apiendpoint_target_id'), table_name='apiendpoint')
    op.drop_table('apiendpoint')
    op.drop_index(op.f('ix_workspacemembership_workspace_id'), table_name='workspacemembership')
    op.drop_index(op.f('ix_workspacemembership_user_id'), table_name='workspacemembership')
    op.drop_table('workspacemembership')
    op.drop_table('target')
    op.drop_table('policyrule')
    op.drop_index(op.f('ix_githubinstallation_installation_id'), table_name='githubinstallation')
    op.drop_index(op.f('ix_githubinstallation_github_app_config_id'), table_name='githubinstallation')
    op.drop_table('githubinstallation')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('platformconfig')
    op.drop_table('organization')
    op.drop_index(op.f('ix_githubappconfig_setup_token'), table_name='githubappconfig')
    op.drop_table('githubappconfig')
    # ### end Alembic commands ###
