"""add mass cicd rollout templates (#35)

Adds `PipelineWorkflowTemplate` (Custom Workflow Builder: a workspace-scoped
named, ordered scanner step list; see app.core.pipeline_workflow) and two
new columns on `PipelineIntegrationBatch` (`scope_label`, added for #35's
scope-based "mass rollout"; `workflow_template_id`, an optional FK to the
template used for that rollout's generated YAML). #68's original manual
bulk-integrate flow is unaffected: existing rows backfill `scope_label` to
""  and `workflow_template_id` stays null.

Hand-checked after `alembic revision --autogenerate`: dropped an unrelated
`slarule.severity` VARCHAR->Enum column-type change the autogenerate diff
picked up (a pre-existing SQLModel/Postgres reflection quirk unrelated to
this issue; see ARCHITECTURE.md's "hand-check it" migration convention),
and named the new foreign key constraint explicitly instead of leaving it
autogenerated-anonymous.

Revision ID: 4acb8bec28d5
Revises: df303bb8affa
Create Date: 2026-08-14 08:18:14.440378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4acb8bec28d5'
down_revision: Union[str, None] = 'c4d8e21a9f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'pipelineworkflowtemplate',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workspace_id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('steps', sa.JSON(), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_pipelineworkflowtemplate_workspace_id'), 'pipelineworkflowtemplate', ['workspace_id'], unique=False
    )
    op.add_column(
        'pipelineintegrationbatch',
        sa.Column('scope_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''),
    )
    op.add_column('pipelineintegrationbatch', sa.Column('workflow_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_pipelineintegrationbatch_workflow_template_id',
        'pipelineintegrationbatch',
        'pipelineworkflowtemplate',
        ['workflow_template_id'],
        ['id'],
    )
    # Drop the server_default once existing rows are backfilled, new rows
    # always set scope_label explicitly (either "" from #68's manual flow or
    # a real label from #35's mass rollout), same as every other non-null
    # str column in this file that isn't meant to silently default forever.
    op.alter_column('pipelineintegrationbatch', 'scope_label', server_default=None)


def downgrade() -> None:
    op.drop_constraint(
        'fk_pipelineintegrationbatch_workflow_template_id', 'pipelineintegrationbatch', type_='foreignkey'
    )
    op.drop_column('pipelineintegrationbatch', 'workflow_template_id')
    op.drop_column('pipelineintegrationbatch', 'scope_label')
    op.drop_index(op.f('ix_pipelineworkflowtemplate_workspace_id'), table_name='pipelineworkflowtemplate')
    op.drop_table('pipelineworkflowtemplate')
