"""backfill the finding/scan query indexes the models already declare (#217)

Revision ID: b1d4f7a09c62
Revises: c3e8b7a2d4f1
Create Date: 2026-09-13

Hand-written, not autogenerated.

These five indexes are declared `index=True` on the models
(`Finding.target_id`, `Finding.branch`, `Finding.priority_score`,
`Finding.state`, `Scan.target_id`) and they are already created by the
initial revision, 404553cc4bf6, which emits `ix_finding_branch`,
`ix_finding_dedup_hash`, `ix_finding_priority_score`, `ix_finding_state`,
`ix_finding_target_id` and `ix_scan_target_id`. A database built by running
the chain from scratch therefore has them.

Databases that predate the chain do not. Before #58, `init_db()` was
`SQLModel.metadata.create_all(engine)` (see app/core/db.py's docstring);
those databases were *stamped* at 404553cc4bf6 rather than built by it, so
whatever `create_all` happened to produce at that moment is what they still
have. That is why `--autogenerate` run against a deployed database keeps
proposing these five indexes as additions even though the chain already
creates them -- the drift reported in #217.

Consequences for how this migration is written:

* Every statement is `IF NOT EXISTS`. On a chain-built database all five
  already exist and a plain `op.create_index` would abort the upgrade with
  "relation already exists"; on a drifted database the missing ones get
  created. Both cases have to pass, because `init_db()` runs
  `alembic upgrade head` on application startup and a failure here is a
  failure to boot.

* On PostgreSQL they are built `CONCURRENTLY`, inside an
  `autocommit_block()` because CONCURRENTLY cannot run inside a transaction.
  The locking cost is the reason: a plain `CREATE INDEX` takes a SHARE lock
  on `finding` for the whole build, which blocks every INSERT, UPDATE and
  DELETE against it until it finishes. `finding` is this platform's largest
  table and ingestion writes to it continuously, so on a large deployment
  that is a write outage lasting as long as the build, taken during startup,
  when nobody is necessarily watching. CONCURRENTLY takes longer and scans
  the table twice, but it does not block writes.

  The trade-off CONCURRENTLY brings: if it is interrupted it can leave an
  INVALID index behind, which continues to cost writes without ever being
  used by the planner. If that happens, `\\d finding` marks the index INVALID;
  the fix is `DROP INDEX CONCURRENTLY <name>;` and re-running this revision.

* Non-PostgreSQL targets (the SQLite engines the test suite builds) get a
  plain `CREATE INDEX IF NOT EXISTS`; SQLite has no CONCURRENTLY and no
  concurrent writers to protect.

Scope note: this revision does nothing but add these indexes. The rest of the
drift #217 catalogues -- the `platformconfig` NOT NULL flips, the
`apitoken.scope` and `slarule.severity` enum conversions, and the
`apitoken.token_hash` constraint swap -- is deliberately not here. Each of
those rewrites or validates existing rows and fails outright on a single bad
one, so each needs a data audit first; they are tracked with their audit
queries in #437. The orphaned `discoveredendpoint` table is #438.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1d4f7a09c62"
down_revision: Union[str, None] = "c3e8b7a2d4f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (index name, table, column). Names match what SQLModel's `index=True`
# produces and what 404553cc4bf6 already creates, so that once these exist
# autogenerate matches them by name and stops proposing them.
INDEXES: tuple[tuple[str, str, str], ...] = (
    ("ix_finding_target_id", "finding", "target_id"),
    ("ix_finding_branch", "finding", "branch"),
    ("ix_finding_priority_score", "finding", "priority_score"),
    ("ix_finding_state", "finding", "state"),
    ("ix_scan_target_id", "scan", "target_id"),
)


def upgrade() -> None:
    is_postgres = op.get_bind().dialect.name == "postgresql"

    if not is_postgres:
        for name, table, column in INDEXES:
            op.execute(f'CREATE INDEX IF NOT EXISTS {name} ON "{table}" ("{column}")')
        return

    # CONCURRENTLY is illegal inside a transaction; autocommit_block drops
    # out of the migration's transaction for the duration.
    with op.get_context().autocommit_block():
        for name, table, column in INDEXES:
            op.execute(
                f'CREATE INDEX CONCURRENTLY IF NOT EXISTS {name} ON "{table}" ("{column}")'
            )


def downgrade() -> None:
    """Deliberately a no-op.

    These indexes are not this revision's to remove. 404553cc4bf6 creates all
    five, and the models declare all five; dropping them on the way down
    would leave a chain-built database missing indexes its own initial
    revision created, which is a worse state than the one this revision was
    written to fix. This revision only ever *adds* what was already supposed
    to be there, so going back down has nothing to undo.

    If you genuinely need one of these gone, drop it explicitly (with
    `DROP INDEX CONCURRENTLY` on PostgreSQL) and remove the matching
    `index=True` from the model in the same change, so the two do not drift
    apart again -- which is the whole subject of #217.
    """
