"""add ai_analysis_run 122

Revision ID: b28cc5c6bb24
Revises: 9dde01b530db
Create Date: 2026-08-14 19:02:18.722028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b28cc5c6bb24'
down_revision: Union[str, None] = '9dde01b530db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aianalysisrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'finding_id', name='uq_ai_analysis_run_user_finding')
    )
    op.create_index(op.f('ix_aianalysisrun_finding_id'), 'aianalysisrun', ['finding_id'], unique=False)
    op.create_index(op.f('ix_aianalysisrun_last_analyzed_at'), 'aianalysisrun', ['last_analyzed_at'], unique=False)
    op.create_index(op.f('ix_aianalysisrun_user_id'), 'aianalysisrun', ['user_id'], unique=False)
    # NOTE: autogenerate also detected an unrelated pre-existing drift
    # (slarule.severity VARCHAR -> Enum) between the live DB and the model
    # definitions. That's not part of issue #122's scope, so it's
    # deliberately left out of this migration rather than folded in here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aianalysisrun_user_id'), table_name='aianalysisrun')
    op.drop_index(op.f('ix_aianalysisrun_last_analyzed_at'), table_name='aianalysisrun')
    op.drop_index(op.f('ix_aianalysisrun_finding_id'), table_name='aianalysisrun')
    op.drop_table('aianalysisrun')
    # ### end Alembic commands ###
